Updated Roster Admin
UWCubeSat/hsl-website pull request #3
Opened 2023-09-05 23:18 UTC by manforowicz

## Added new admin

- Added new admin role descriptions to former member descriptions, separated by line break.

```Marc Alwan (Treasurer, Advertising Lead)
Marcin Anforowicz (Webmaster)
Alex Billesberger (Mechanical Lead)
Ellie Brosius (Electrical Lead)
Karen Haining (Recruiter, Training Lead)
Aileen Laubach (Secretary)
Avery Mortimore (Chief Engineer)
Tri Nguyen (Project Manager, Systems Engineer)
Alnis Smidchens (President)
Edward Zhang (Vice President, Software Lead)
```

## Removed the following from admin:
```
Grace Kelly - Moved to Alumni
Mark Polyakov - Moved to Member: "Star Tracker"
Aryan Sharma - Moved to Member: "Software" (that was part of his previous role description)
Ryan Welch - Moved to Member: "Reaction Wheels Lead"
Stephanie Geeson - Moved to Member: TODO, NO DESCRIPTION ADDED YET!
```

I did my best, but chances are there are at mistakes ;)

2023-09-05 23:48 UTC, AlnisS requested changes
Content looks good for the most part! Added some recommendations for minor changes.

2023-09-05 23:48 UTC, AlnisS commented on team.js
> +    name: "Stephanie Geeson",
Stephanie has now graduated — I'd recommend moving to Alumni.

I'd leave the role as "Vice President" (i.e. former vice president) since we have the same for some other alumni.

2023-09-05 23:48 UTC, AlnisS commented on team.js
> +    name: "Aryan Sharma",
I haven't heard from Aryan in a while and he's gone inactive on Slack — I think it's safe to move him to "Alumni"

2023-09-05 23:48 UTC, AlnisS commented on team.js
> +    name: "Mark Polyakov",
I've messaged Mark to ask whether he wants to be listed under members (as an "industry mentor") or alumni. I think we can leave it as-is-here for now until we hear back — this shouldn't block merging.

2023-09-05 23:48 UTC, AlnisS commented on team.js
Let's remove `style="max-width: 700px"` from `team.html` — now that the leadership team is larger, having this restricted width makes it vertically longer than needed.

2023-09-06 00:05 UTC, manforowicz commented
Ok, I added the requested changes.

2023-09-08 20:22 UTC, merged