Added members and board
UWCubeSat/hsl-website pull request #36
Opened 2024-06-03 04:12 UTC by manforowicz

- Added and updated a few members from the HSL Website Roster Form (including the one I mistakenly posted).
- Created board section, and moved members correspondingly.
- Moved Alnis to alumni :sob:. Thank you for your service!

2024-06-03 04:34 UTC, AlnisS requested changes
Added a few comments for revisions --- LMK if there's anything unclear or you'd like to discuss!

2024-06-03 04:34 UTC, AlnisS commented on team.html
> +    <h2>Board<a href="#leadership" class="anchor" id="leadership"><span class="material-symbols-outlined">link</span></a></h2>
Should we change the href and id to "board" for the board section? (from the old leadership section)

2024-06-03 04:34 UTC, AlnisS commented on team.html
> +    <div class="team-member-container">
I should not have the large card, only Prof. Winglee should have that. Instead, I should be part of the general list of alumni.

2024-06-03 04:34 UTC, AlnisS commented on team.js
> -    "roles": "Secretary<br>Structures",
Should we remove titles that no longer apply with the formation of the board (e.g. "Secretary") or should we prepend "Former" i.e. make it "Former Secretary" or something else?

2024-06-03 04:34 UTC, AlnisS commented on team.html
> +    <h2>Board<a href="#leadership" class="anchor" id="leadership"><span class="material-symbols-outlined">link</span></a></h2>
We should include Yoshi, Jasmine, Rassa even though they have not filled out roster form yet, as they are board members, and this information is important

2024-06-03 06:01 UTC, AlnisS commented on team.html
> +    <h2>Board<a href="#leadership" class="anchor" id="leadership"><span class="material-symbols-outlined">link</span></a></h2>
Update: Rassa and Yoshi have submitted roster form + provided pictures: https://docs.google.com/spreadsheets/d/1ZOkDjnR4W-MiwPH_oDmwIx-mfvzyHaBiJyjTrjWz9SE/edit

2024-06-03 15:22 UTC, manforowicz commented on team.html
> +    <h2>Board<a href="#leadership" class="anchor" id="leadership"><span class="material-symbols-outlined">link</span></a></h2>
I just added Yoshi and Rassa, but I messaged Jasmine, and will wait for a response. For privacy reasons I'd prefer to get confirmation before putting their name on the website.

2024-06-03 15:23 UTC, manforowicz commented on team.js
> -    "roles": "Secretary<br>Structures",
I added a commit where I prepend all leadership roles with "former".

2024-06-03 15:23 UTC, manforowicz commented on team.html
> +    <div class="team-member-container">
Sounds good!

2024-06-03 15:24 UTC, manforowicz commented on team.html
> +    <h2>Board<a href="#leadership" class="anchor" id="leadership"><span class="material-symbols-outlined">link</span></a></h2>
I just changed the anchor to "board", but also added an invisible one to "leadership", so that old links aren't broken.

2024-06-22 03:30 UTC, manforowicz commented
I just updated Ellison's photo and added a line break to Cameron's description. I think all the issues have been addressed.

2024-06-26 17:21 UTC, AlnisS approved these changes
Great work! Looks good to me. Thanks for putting this together.

2024-06-26 17:21 UTC, AlnisS commented on images/members/ellison-dykes.jpg
Looks like this photo is 600x600px instead of 400x400px. Not a big deal, but could be good to have consistency.

2024-06-29 17:36 UTC, merged